"""add_extra_data_jsonb

Revision ID: 159de8fc55fb
Revises: 05d39e86f1a6
Create Date: 2026-05-17 13:15:32.212857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '159de8fc55fb'
down_revision: Union[str, Sequence[str], None] = '05d39e86f1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))

    # Migrate existing data from old columns into extra_data JSONB
    old_columns = [
        'model', 'serial_no', 'range_value', 'accuracy', 'scale_interval',
        'manufacture_date', 'manufacturer', 'purchase_date', 'price',
        'keeper', 'location', 'cal_agency', 'certificate_no', 'cert_confirmed',
        'metrology_characteristic', 'cal_method', 'remark', 'last_cal_cost',
    ]
    for col in old_columns:
        op.execute(f"UPDATE instruments SET extra_data = jsonb_set(extra_data, '{{{col}}}', to_jsonb({col})) WHERE {col} IS NOT NULL")

    op.drop_column('instruments', 'price')
    op.drop_column('instruments', 'accuracy')
    op.drop_column('instruments', 'cert_confirmed')
    op.drop_column('instruments', 'purchase_date')
    op.drop_column('instruments', 'certificate_no')
    op.drop_column('instruments', 'remark')
    op.drop_column('instruments', 'model')
    op.drop_column('instruments', 'scale_interval')
    op.drop_column('instruments', 'serial_no')
    op.drop_column('instruments', 'keeper')
    op.drop_column('instruments', 'metrology_characteristic')
    op.drop_column('instruments', 'manufacture_date')
    op.drop_column('instruments', 'cal_method')
    op.drop_column('instruments', 'manufacturer')
    op.drop_column('instruments', 'last_cal_cost')
    op.drop_column('instruments', 'location')
    op.drop_column('instruments', 'range_value')
    op.drop_column('instruments', 'cal_agency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('cal_agency', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('range_value', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('last_cal_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('manufacturer', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('cal_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('manufacture_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('metrology_characteristic', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('keeper', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('serial_no', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('scale_interval', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('model', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('remark', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('certificate_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('cert_confirmed', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('accuracy', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('instruments', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('instruments', 'extra_data')
    # ### end Alembic commands ###
